//<auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace BloggingPlatform.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddTableBlogPostAndComments : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "BlogPosts",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    UserId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    Title = table.Column<string>(type: "nvarchar(255)", maxLength: 255, nullable: false),
                    Content = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    CreatedAt = table.Column<DateTime>(type: "datetime2", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_BlogPosts", x => x.Id);
                    table.ForeignKey(
                        name: "FK_BlogPosts_Users_UserId",
                        column: x => x.UserId,
                        principalTable: "Users",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "Comments",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    UserId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    BlogPostId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    CommenterName = table.Column<string>(type: "nvarchar(255)", maxLength: 255, nullable: false),
                    CommenterEmail = table.Column<string>(type: "nvarchar(255)", maxLength: 255, nullable: false),
                    Content = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    CreatedAt = table.Column<DateTime>(type: "datetime2", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Comments", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Comments_BlogPosts_BlogPostId",
                        column: x => x.BlogPostId,
                        principalTable: "BlogPosts",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_Comments_Users_UserId",
                        column: x => x.UserId,
                        principalTable: "Users",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.InsertData(
                table: "BlogPosts",
                columns: new[] { "Id", "Content", "CreatedAt", "Title", "UserId" },
                values: new object[,]
                {
                    { new Guid("597467f9-00bd-481c-b48a-d1ce44b1f458"), "This is the content of the eighth post.", new DateTime(2024, 7, 26, 22, 31, 32, 120, DateTimeKind.Utc).AddTicks(3911), "Eighth Post", new Guid("e3f54c19-7c26-48d6-8696-1359e7e88f86") },
                    { new Guid("691bb48e-4acb-4797-ad80-a048107f74c7"), "This is the content of the first post.", new DateTime(2024, 7, 26, 22, 31, 32, 120, DateTimeKind.Utc).AddTicks(3765), "First Post", new Guid("3670dc16-c548-4142-a4e8-ccd6691dcb6c") },
                    { new Guid("8cc0d1e3-5613-4cae-a3a2-312c248b6e41"), "This is the content of the seventh post.", new DateTime(2024, 7, 26, 22, 31, 32, 120, DateTimeKind.Utc).AddTicks(3874), "Seventh Post", new Guid("3670dc16-c548-4142-a4e8-ccd6691dcb6c") },
                    { new Guid("9c137fed-cf93-4ad7-91dc-ff665b96f338"), "This is the content of the fifth post.", new DateTime(2024, 7, 26, 22, 31, 32, 120, DateTimeKind.Utc).AddTicks(3857), "Fifth Post", new Guid("3670dc16-c548-4142-a4e8-ccd6691dcb6c") },
                    { new Guid("9e804865-4ffa-4084-b617-38bf5e6463de"), "This is the content of the third post.", new DateTime(2024, 7, 26, 22, 31, 32, 120, DateTimeKind.Utc).AddTicks(3844), "Third Post", new Guid("3670dc16-c548-4142-a4e8-ccd6691dcb6c") },
                    { new Guid("afc8ea8d-e918-4c68-a896-8a64d9e2b3ff"), "This is the content of the second post.", new DateTime(2024, 7, 26, 22, 31, 32, 120, DateTimeKind.Utc).AddTicks(3777), "Second Post", new Guid("e3f54c19-7c26-48d6-8696-1359e7e88f86") },
                    { new Guid("c69665cf-830c-493a-8be3-d985fd978f55"), "This is the content of the fourth post.", new DateTime(2024, 7, 26, 22, 31, 32, 120, DateTimeKind.Utc).AddTicks(3850), "Fourth Post", new Guid("e3f54c19-7c26-48d6-8696-1359e7e88f86") },
                    { new Guid("f27d066d-c3c0-461b-9153-a7fe3cc34cce"), "This is the content of the ninth post.", new DateTime(2024, 7, 26, 22, 31, 32, 120, DateTimeKind.Utc).AddTicks(3920), "Ninth Post", new Guid("3670dc16-c548-4142-a4e8-ccd6691dcb6c") },
                    { new Guid("fae6e7cf-c9cc-489f-a3ae-126e2505e200"), "This is the content of the sixth post.", new DateTime(2024, 7, 26, 22, 31, 32, 120, DateTimeKind.Utc).AddTicks(3865), "Sixth Post", new Guid("e3f54c19-7c26-48d6-8696-1359e7e88f86") }
                });

            migrationBuilder.InsertData(
                table: "Comments",
                columns: new[] { "Id", "BlogPostId", "CommenterEmail", "CommenterName", "Content", "CreatedAt", "UserId" },
                values: new object[,]
                {
                    { new Guid("d78febcf-f7f1-49c3-b8a0-e920e8e701e0"), new Guid("afc8ea8d-e918-4c68-a896-8a64d9e2b3ff"), "mahmoud12345@gmail.com", "mahmoud", "This is a comment on the second post.", new DateTime(2024, 7, 26, 22, 31, 32, 121, DateTimeKind.Utc).AddTicks(6195), new Guid("3670dc16-c548-4142-a4e8-ccd6691dcb6c") },
                    { new Guid("e867ffdf-a5fa-4c60-a446-f9aa54695657"), new Guid("691bb48e-4acb-4797-ad80-a048107f74c7"), "ahmed@gmail.com", "ahmed", "This is a comment on the first post.", new DateTime(2024, 7, 26, 22, 31, 32, 121, DateTimeKind.Utc).AddTicks(6232), new Guid("e3f54c19-7c26-48d6-8696-1359e7e88f86") }
                });

            migrationBuilder.CreateIndex(
                name: "IX_BlogPosts_UserId",
                table: "BlogPosts",
                column: "UserId");

            migrationBuilder.CreateIndex(
                name: "IX_Comments_BlogPostId",
                table: "Comments",
                column: "BlogPostId");

            migrationBuilder.CreateIndex(
                name: "IX_Comments_UserId",
                table: "Comments",
                column: "UserId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Comments");

            migrationBuilder.DropTable(
                name: "BlogPosts");
        }
    }
}
